import {
  Mail,
  BriefcaseBusiness,
  Building,
  MessageCircle,
} from "lucide-react";
import ContactForm from "./_components/form";
import FAQs from "./_components/faqs";
import CTA from "./_components/cta";

export default function Contact() {
  return (
    <div className="w-full relative min-h-screen bg-black">
      <div
        className="max-w-7xl mx-auto px-6 py-24 space-y-14"
        id="contact-view-container"
      >
        <section
          className="text-center max-w-3xl mx-auto space-y-4"
          id="contact-header"
        >
          <h1 className="text-5xl md:text-6xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-white via-purple-100 to-purple-500 drop-shadow-[0_0_15px_rgba(168,85,247,0.3)] pb-2 tracking-tight">
            Let's Build the Future
          </h1>

          <p className="mt-6 max-w-2xl mx-auto text-lg text-gray-300 leading-relaxed text-center">
            Ready to deploy Next Frontier digital assets? Submit your
            specifications to receive a customized Solutions Proposal instantly
            generated by our engineering matrices.
          </p>
        </section>

        <section
          className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-8 items-stretch"
          id="contact-content"
        >
          <div className="p-8 text-white rounded-3xl backdrop-blur-md bg-black/40 ring-1 ring-purple-500/30 transition-all duration-500 ease-in-out [box-shadow:inset_0_1px_0_0_rgba(168,85,247,0.4),inset_0_-1px_0_0_rgba(168,85,247,0.1),inset_1px_0_0_0_rgba(168,85,247,0.2),inset_-1px_0_0_0_rgba(168,85,247,0.2),0_0_24px_0_rgba(168,85,247,0.15)] hover:ring-purple-400/60 hover:[box-shadow:inset_0_1px_0_0_rgba(168,85,247,0.6),inset_0_-1px_0_0_rgba(168,85,247,0.2),inset_1px_0_0_0_rgba(168,85,247,0.3),inset_-1px_0_0_0_rgba(168,85,247,0.3),0_0_60px_8px_rgba(168,85,247,0.35),0_0_120px_16px_rgba(168,85,247,0.15)] h-full flex flex-col justify-center">
            
            <div className="space-y-4 text-left">
              <h3 className="text-3xl font-bold text-white tracking-wide">
                Communication Channels
              </h3>

              <p className="text-[#c2c6d6] text-lg leading-relaxed max-w-md">
                We work with startups, businesses, and enterprises worldwide.
              </p>
            </div>

            <div className="my-8 h-px w-full bg-gradient-to-r from-purple-500/50 via-white/20 to-transparent" />

            <div className="space-y-2">
              
              <div className="group flex gap-5 p-4 -ml-4 rounded-2xl transition-all duration-300 hover:bg-white/5 hover:border-white/10 border border-transparent cursor-pointer">
                <div className="flex items-center justify-center w-12 h-12 rounded-full bg-purple-500/10 transition-all duration-300 group-hover:bg-purple-500/20 group-hover:shadow-[0_0_15px_rgba(168,85,247,0.3)] shrink-0">
                  <Mail className="w-6 h-6 text-purple-400 transition-transform duration-300 group-hover:scale-110 group-hover:text-purple-300" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-lg transition-colors duration-300 group-hover:text-purple-200">Email</h4>
                  <p className="text-sm text-[#c2c6d6] leading-relaxed mt-1">
                    Primary communication for project discussions.
                  </p>
                </div>
              </div>

              <div className="group flex gap-5 p-4 -ml-4 rounded-2xl transition-all duration-300 hover:bg-white/5 hover:border-white/10 border border-transparent cursor-pointer">
                <div className="flex items-center justify-center w-12 h-12 rounded-full bg-purple-500/10 transition-all duration-300 group-hover:bg-purple-500/20 group-hover:shadow-[0_0_15px_rgba(168,85,247,0.3)] shrink-0">
                  <BriefcaseBusiness className="w-6 h-6 text-purple-400 transition-transform duration-300 group-hover:scale-110 group-hover:text-purple-300" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-lg transition-colors duration-300 group-hover:text-purple-200">LinkedIn</h4>
                  <p className="text-sm text-[#c2c6d6] leading-relaxed mt-1">
                    Strategic collaborations, networking, and partnership
                    opportunities.
                  </p>
                </div>
              </div>

              <div className="group flex gap-5 p-4 -ml-4 rounded-2xl transition-all duration-300 hover:bg-white/5 hover:border-white/10 border border-transparent cursor-pointer">
                <div className="flex items-center justify-center w-12 h-12 rounded-full bg-purple-500/10 transition-all duration-300 group-hover:bg-purple-500/20 group-hover:shadow-[0_0_15px_rgba(168,85,247,0.3)] shrink-0">
                  <Building className="w-6 h-6 text-purple-400 transition-transform duration-300 group-hover:scale-110 group-hover:text-purple-300" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-lg transition-colors duration-300 group-hover:text-purple-200">
                    Github Organization
                  </h4>
                  <p className="text-sm text-[#c2c6d6] leading-relaxed mt-1">
                    Corporate inquiries, enterprise engagements, and company
                    relations.
                  </p>
                </div>
              </div>

              <div className="group flex gap-5 p-4 -ml-4 rounded-2xl transition-all duration-300 hover:bg-white/5 hover:border-white/10 border border-transparent cursor-pointer">
                <div className="flex items-center justify-center w-12 h-12 rounded-full bg-purple-500/10 transition-all duration-300 group-hover:bg-purple-500/20 group-hover:shadow-[0_0_15px_rgba(168,85,247,0.3)] shrink-0">
                  <MessageCircle className="w-6 h-6 text-purple-400 transition-transform duration-300 group-hover:scale-110 group-hover:text-purple-300" />
                </div>
                <div>
                  <h4 className="font-semibold text-white text-lg transition-colors duration-300 group-hover:text-purple-200">WhatsApp</h4>
                  <p className="text-sm text-[#c2c6d6] leading-relaxed mt-1">
                    Quick consultations and urgent inquiries.
                  </p>
                </div>
              </div>

            </div>
          </div>

          <div id="contact-form" className="h-full">
            <ContactForm />
          </div>
        </section>

        <section id="faq">
          <div className="min-h-[400px]  max-w-6xl mx-auto">
            <FAQs />
          </div>
        </section>

        <section id="cta">
          <div className="min-h-[250px]  flex items-center justify-center max-w-5xl mx-auto">
            <CTA />
          </div>
        </section>
      </div>
    </div>
  );
}