import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Oswald,
  Inter,
  Space_Grotesk,
  Sora,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/Navbar";
import Footer from "@/_components/Footer";
import CursorGlitter from "@/_components/CursorGlitter"; // 1. Add the import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  // weight: ["300", "400", "500", "600", "700"],
  // display: "swap",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  // weight: ["300", "400", "500", "600", "700"],
  // display: "swap",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plusjakartasans",
});

// const spaceGrotesk = Space_Grotesk({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${plusJakartaSans.className} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. Place the component anywhere inside the body */}
        <CursorGlitter />

        <Navbar />

        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
